server:
  port: 9011
spring:
  application:
    name: soc-manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
zuul:
  routes:
    soc-base:
      path: /base/**
      serviceId: soc-base
