server:
  port: 9012
spring:
  application:
    name: soc-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
zuul:
  routes:
    soc-base:
      path: /base/**
      serviceId: soc-base
    soc-user:
      path: /user/**
      serviceId: soc-user
    soc-qa:
      path: /qa/**
      serviceId: soc-qa
