server:
  port: 9007
spring:
  application:
    name: soc-search
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: my-pc:9300
      cluster-name: elasticsearch
