server:
  port: 12000
spring:
  application:
    name: soc-config
  cloud:
    config:
      server:
        git:
          uri: http://my-pc:880/root/soc.git
  rabbitmq:
    host: my-pc
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh