server:
  port: 12000
spring:
  application:
    name: soc-config
  cloud:
    config:
      server:
        git:
          uri: http://172.17.0.1:880/root/soc.git
  rabbitmq:
    host: 172.17.0.1
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:6868/eureka/
  instance:
    ip-address: 172.17.0.1
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh